export const PacienteAGineco = {
  fum: null,
  menarca: '',
  irs: '',
  gestas: '',
  partos: '',
  cesareas: '',
  abortos: '',
  ciclos: '',
  menopuasia: '',
  anticoncepcion_q: null,
  anticoncepcion_t: '',
  diu: null,
  diu_t: '',
  implante: null,
  fup: null,
  fup_t: '',
  notas: '',
}
